version: "3.0.0"
services:
  javaBuilder:
    build:
      context: ..
      dockerfile: ./artemis-docker/Dockerfile-build
    image: artemis-docker-base
    command: >
      bash -c "pwd && ls -lisa && mvn -q clean install -DskipTests -DskipITs -DskipDocs -DskipDocker -DskipDoc"
    volumes:
      - ./target:/root/artemis-build/